import test from 'node:test';
import assert from 'node:assert/strict';
import {createWebServer,validateRecord,validateVaultKey} from '../src/server.js';
import {analyze,generatePassword,digest,encrypt,decrypt} from '../../public/security.js';
test('rule weights and thresholds match iOS',()=>{assert.equal(analyze('Hi','message').riskScore,0);const r=analyze('من البنك عاجل أرسل رمز التحقق','message');assert.equal(r.riskScore,93);assert.equal(r.riskLevelRaw,'critical');assert.ok(r.signals.some(s=>s.id==='otpRequest'));assert.equal(analyze('https://example.com','link').riskScore,0);});
test('password generator guarantees selected groups',()=>{for(let i=0;i<30;i++){const p=generatePassword(20,['ABC','abc','123','!@#']);assert.equal(p.length,20);for(const r of [/[A-C]/,/[a-c]/,/[1-3]/,/[!@#]/])assert.match(p,r);}});
test('CryptoKit-compatible PBKDF2/AES-GCM package round trip and tamper protection',async()=>{const p=await encrypt('حصن يحمي بياناتك','strong-password');assert.equal(await decrypt(p,'strong-password'),'حصن يحمي بياناتك');await assert.rejects(decrypt(p,'wrong'));assert.equal(await digest('abc'),'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');});
test('record validation clamps scores and redacts numbers',()=>{const r=validateRecord({...analyze('OTP 123456'),contentPreview:'OTP 123456',riskScore:150});assert.equal(r.riskScore,100);assert.equal(r.contentPreview,'OTP ••••');assert.throws(()=>validateRecord({}));assert.throws(()=>validateVaultKey('short'));});
test('web routes serve static assets, require CSRF, never expose vault in session',async()=>{process.env.HISN_API_ACCESS_TOKEN='a'.repeat(64);const server=createWebServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{assert.equal((await fetch(base+'/')).status,200);assert.equal((await fetch(base+'/app.js')).status,200);const session=await fetch(base+'/api/session');const cookie=session.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);const data=await session.json();assert.equal(data.connected,false);assert.equal(data.vault,undefined);assert.equal((await fetch(base+'/api/vault/connect',{method:'POST',headers:{cookie},body:'{}'})).status,403);assert.equal((await fetch(base+'/api/history',{headers:{cookie}})).status,400);assert.equal((await fetch(base+'/.env')).status,404);}finally{server.close();}});
